# Generated by Django 6.0.6 on 2026-07-05 02:47

import django.db.models.deletion
from django.db import migrations, models


def _seed_drive_category(apps, schema_editor):
    category = apps.get_model("catalog", "Category")
    category.objects.get_or_create(slug="drive", defaults={"name": "Drive"})


def _unseed_drive_category(apps, schema_editor):
    apps.get_model("catalog", "Category").objects.filter(slug="drive").delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS timescaledb;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "categories",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_number", models.CharField(max_length=100)),
                ("normalized_model_number", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "product_model",
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("normalized_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "manufacturer",
            },
        ),
        migrations.CreateModel(
            name="ProductFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="families",
                        to="catalog.category",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="families",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product families",
                "db_table": "product_family",
            },
        ),
        migrations.CreateModel(
            name="SourceSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("normalized_name", models.CharField(max_length=100, unique=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manufacturer_store", "Manufacturer store"),
                            ("specialist_reseller", "Storage-specialist reseller"),
                            ("marketplace", "Marketplace"),
                            ("retailer", "Retailer"),
                            ("search_provider", "Search provider"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("region", models.CharField(blank=True, default="US", max_length=10)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "source_site",
            },
        ),
        migrations.CreateModel(
            name="DriveSpec",
            fields=[
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="drive_spec",
                        serialize=False,
                        to="catalog.productmodel",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("hdd", "HDD"), ("ssd", "SSD"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("interface", models.CharField(blank=True, default="", max_length=50)),
                ("form_factor", models.CharField(blank=True, default="", max_length=50)),
                (
                    "capacity_tb",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
                ),
                ("rpm", models.PositiveIntegerField(blank=True, null=True)),
                ("cache_mb", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "recording_tech",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cmr", "CMR"),
                            ("smr_dm", "SMR (device-managed)"),
                            ("smr_hm", "SMR (host-managed)"),
                            ("smr_unknown", "SMR (type unknown)"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("plp", models.BooleanField(blank=True, null=True)),
                ("market_tier", models.CharField(blank=True, default="", max_length=50)),
                ("model_family", models.CharField(blank=True, default="", max_length=100)),
                (
                    "dwpd",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                ("workload_tb_year", models.PositiveIntegerField(blank=True, null=True)),
                ("tbw", models.PositiveIntegerField(blank=True, null=True)),
                ("sector_format", models.CharField(blank=True, default="", max_length=20)),
                ("sed", models.BooleanField(blank=True, null=True)),
                ("spec_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "drive_spec",
            },
        ),
        migrations.AddField(
            model_name="productmodel",
            name="manufacturer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="catalog.manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="product_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="models",
                to="catalog.productfamily",
            ),
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("recertified", "Recertified"),
                            ("refurbished", "Refurbished"),
                            ("used", "Used"),
                            ("open_box", "Open box"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "packaging",
                    models.CharField(
                        choices=[
                            ("retail", "Retail"),
                            ("bulk", "Bulk/OEM"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "recert_channel",
                    models.CharField(
                        choices=[
                            ("factory", "Manufacturer recertified"),
                            ("seller", "Seller refurbished"),
                            ("none", "Not recertified"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "warranty_channel",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("seller", "Seller"),
                            ("none", "None"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("warranty_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "product_variant",
            },
        ),
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("gtin", "GTIN"),
                            ("upc", "UPC"),
                            ("ean", "EAN"),
                            ("asin", "ASIN"),
                            ("epid", "eBay ePID"),
                            ("mpn", "Manufacturer part number"),
                            ("oem_pn", "OEM part number"),
                            ("retail_pn", "Retail part number"),
                            ("region_pn", "Region/revision part number"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("normalized_alias_text", models.CharField(max_length=200)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("catalog_authoritative", "Catalog authoritative"),
                            ("listing_derived", "Listing derived"),
                            ("manual", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.productmodel",
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.productfamily",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "source_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="catalog.sourcesite",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "product aliases",
                "db_table": "product_alias",
            },
        ),
        migrations.CreateModel(
            name="DriveUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial_number", models.CharField(max_length=100)),
                ("smart_json", models.JSONField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "product_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="units",
                        to="catalog.productmodel",
                    ),
                ),
            ],
            options={
                "db_table": "drive_unit",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_model", "serial_number"),
                        name="drive_unit_unique_serial_per_model",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="productmodel",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "normalized_model_number"),
                name="product_model_identity_anchor",
            ),
        ),
        migrations.AddConstraint(
            model_name="productfamily",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "normalized_name"), name="product_family_unique_per_mfr"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=(
                    "product_model",
                    "condition",
                    "packaging",
                    "recert_channel",
                    "warranty_channel",
                ),
                name="product_variant_unique_sellable_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("product_family__isnull", True),
                        ("product_model__isnull", False),
                        ("product_variant__isnull", True),
                    ),
                    models.Q(
                        ("product_family__isnull", False),
                        ("product_model__isnull", True),
                        ("product_variant__isnull", True),
                    ),
                    models.Q(
                        ("product_family__isnull", True),
                        ("product_model__isnull", True),
                        ("product_variant__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="product_alias_exactly_one_grain",
            ),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_kind", ""), _negated=True),
                name="product_alias_source_kind_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("alias_type", "oem_pn"), ("product_variant__isnull", False), _negated=True
                ),
                name="product_alias_oem_pn_not_variant_grain",
            ),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("alias_type", "oem_pn"), _negated=True),
                fields=("alias_type", "normalized_alias_text", "source_site"),
                name="product_alias_single_target_per_site",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="productalias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("alias_type", "oem_pn")),
                fields=(
                    "alias_type",
                    "normalized_alias_text",
                    "source_site",
                    "product_model",
                    "product_family",
                ),
                name="product_alias_oem_multi_target_no_dupes",
                nulls_distinct=False,
            ),
        ),
        migrations.RunPython(_seed_drive_category, _unseed_drive_category),
    ]
