# Generated by Django 6.0.6 on 2026-07-05 02:49

from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(max_length=50)),
                ("endpoint", models.CharField(max_length=255)),
                ("fetched_at", models.DateTimeField()),
                ("request_json", models.JSONField(blank=True, null=True)),
                ("response_json", models.JSONField(blank=True, null=True)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("content_hash", models.CharField(max_length=64)),
                ("http_status", models.PositiveSmallIntegerField()),
                ("parse_version", models.CharField(blank=True, default="", max_length=20)),
            ],
            options={
                "db_table": "raw_payload",
                "indexes": [models.Index(fields=["content_hash"], name="raw_payload_content_hash")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_class", ""), _negated=True),
                        name="raw_payload_retention_class_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expires_at__isnull", True),
                                (
                                    "retention_class__in",
                                    [
                                        "merchant_fact",
                                        "amazon_identifier",
                                        "tavily_extract",
                                        "manufacturer_reference",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("expires_at__isnull", False),
                                (
                                    "retention_class__in",
                                    [
                                        "ebay_listing_observation",
                                        "amazon_ephemeral",
                                        "transient_discovery",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="raw_payload_retention_ttl_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "source_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sellers",
                        to="catalog.sourcesite",
                    ),
                ),
            ],
            options={
                "db_table": "seller",
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("source_listing_key", models.CharField(max_length=255)),
                ("canonical_url", models.URLField(max_length=1000)),
                ("url_hash", models.CharField(max_length=64)),
                ("title_raw", models.TextField()),
                ("title_normalized", models.TextField(blank=True, default="")),
                ("condition_label_raw", models.CharField(blank=True, default="", max_length=255)),
                ("listing_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("page_metadata_json", models.JSONField(blank=True, default=dict)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "source_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="catalog.sourcesite",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="catalog.seller",
                    ),
                ),
            ],
            options={
                "db_table": "listing",
            },
        ),
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(max_length=50)),
                ("checked_at", models.DateTimeField()),
                ("result_json", models.JSONField(blank=True, default=dict)),
                (
                    "drive_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verifications",
                        to="catalog.driveunit",
                    ),
                ),
            ],
            options={
                "db_table": "verification_event",
            },
        ),
        migrations.CreateModel(
            name="OfferSnapshot",
            fields=[
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "listing_id",
                        "observed_at",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("observed_at", models.DateTimeField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("item_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shipping_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "tax_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "total_landed_price",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("item_price"),
                                "+",
                                django.db.models.functions.comparison.Coalesce(
                                    models.F("shipping_price"), models.Value(Decimal("0"))
                                ),
                            ),
                            "+",
                            django.db.models.functions.comparison.Coalesce(
                                models.F("tax_price"), models.Value(Decimal("0"))
                            ),
                        ),
                        output_field=models.DecimalField(decimal_places=2, max_digits=12),
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("out_of_stock", "Out of stock"),
                            ("preorder", "Pre-order"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("quantity_available", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fx_rate",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
                ),
                ("fx_pair", models.CharField(blank=True, default="", max_length=7)),
                ("fx_rate_date", models.DateField(blank=True, null=True)),
                ("fx_source", models.CharField(blank=True, default="", max_length=50)),
                ("extraction_method", models.CharField(blank=True, default="", max_length=50)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("attrs_json", models.JSONField(blank=True, default=dict)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="catalog.listing",
                    ),
                ),
                (
                    "raw_payload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="snapshots",
                        to="catalog.rawpayload",
                    ),
                ),
            ],
            options={
                "db_table": "offer_snapshot",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_class", ""), _negated=True),
                        name="offer_snapshot_retention_class_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expires_at__isnull", True),
                                (
                                    "retention_class__in",
                                    [
                                        "merchant_fact",
                                        "amazon_identifier",
                                        "tavily_extract",
                                        "manufacturer_reference",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("expires_at__isnull", False),
                                (
                                    "retention_class__in",
                                    [
                                        "ebay_listing_observation",
                                        "amazon_ephemeral",
                                        "transient_discovery",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="offer_snapshot_retention_ttl_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(max_length=50)),
                ("query_text", models.TextField()),
                ("query_params_json", models.JSONField(blank=True, default=dict)),
                ("observed_at", models.DateTimeField()),
                ("result_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("result_url", models.URLField(max_length=1000)),
                (
                    "matched_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="search_observations",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "db_table": "search_observation",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_class", ""), _negated=True),
                        name="search_observation_retention_class_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expires_at__isnull", True),
                                (
                                    "retention_class__in",
                                    [
                                        "merchant_fact",
                                        "amazon_identifier",
                                        "tavily_extract",
                                        "manufacturer_reference",
                                    ],
                                ),
                            ),
                            models.Q(
                                ("expires_at__isnull", False),
                                (
                                    "retention_class__in",
                                    [
                                        "ebay_listing_observation",
                                        "amazon_ephemeral",
                                        "transient_discovery",
                                    ],
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="search_observation_retention_ttl_coherent",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="seller",
            constraint=models.UniqueConstraint(
                fields=("source_site", "normalized_name"), name="seller_unique_per_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_class", ""), _negated=True),
                name="listing_retention_class_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            ["ebay_listing_observation", "amazon_ephemeral", "transient_discovery"],
                        ),
                    ),
                    _connector="OR",
                ),
                name="listing_retention_ttl_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("source_site", "source_listing_key"), name="listing_unique_per_site_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_class", ""), _negated=True),
                name="verification_event_retention_class_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            ["ebay_listing_observation", "amazon_ephemeral", "transient_discovery"],
                        ),
                    ),
                    _connector="OR",
                ),
                name="verification_event_retention_ttl_coherent",
            ),
        ),
    ]
