# Generated by Django 6.0.6 on 2026-07-05 08:10

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_offer_snapshot_hypertable"),
    ]

    operations = [
        migrations.CreateModel(
            name="FxRateDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rate_date", models.DateField()),
                ("base", models.CharField(max_length=3)),
                ("quote", models.CharField(default="USD", max_length=3)),
                ("rate", models.DecimalField(decimal_places=6, max_digits=12)),
                ("source", models.CharField(default="frankfurter", max_length=50)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fx_rate_daily",
            },
        ),
        migrations.CreateModel(
            name="SchedulerCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=50, unique=True)),
                ("state_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "scheduler_checkpoint",
            },
        ),
        migrations.CreateModel(
            name="ScraperRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "run_kind",
                    models.CharField(
                        choices=[
                            ("full", "Full pipeline"),
                            ("heartbeat", "Availability heartbeat"),
                            ("reference", "Reference-catalog ingest"),
                            ("probe", "Recovery probe"),
                        ],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=10,
                    ),
                ),
                (
                    "failure_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("transient", "Transient"),
                            ("anti_bot", "Anti-bot / soft block"),
                            ("parser_rot", "Parser rot"),
                            ("degradation", "Degradation"),
                            ("unknown", "Unknown (escalate)"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("records_fetched", models.PositiveIntegerField(default=0)),
                ("records_valid", models.PositiveIntegerField(default=0)),
                ("listings_upserted", models.PositiveIntegerField(default=0)),
                ("snapshots_appended", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True, default="")),
                ("detail_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "scraper_runs",
            },
        ),
        migrations.CreateModel(
            name="SourceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("t0", "T0 — official API"),
                            ("t1", "T1 — manufacturer-direct"),
                            ("t2", "T2 — specialist/VAR"),
                            ("t3", "T3 — anti-bot-exposed"),
                            ("t4", "T4 — refurb/regional"),
                        ],
                        max_length=2,
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("cadence_baseline_s", models.PositiveIntegerField()),
                ("cadence_ceiling_s", models.PositiveIntegerField()),
                ("current_interval_s", models.PositiveIntegerField()),
                (
                    "volatility_profile",
                    models.CharField(
                        choices=[
                            ("drop_prone", "Drop-prone"),
                            ("churning", "Churning"),
                            ("stable", "Stable"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                (
                    "cheap_signal",
                    models.CharField(
                        choices=[
                            ("shopify_products_json", "Shopify /products.json"),
                            ("woocommerce_store_api", "WooCommerce Store API"),
                            ("ebay_browse", "eBay Browse API"),
                            ("occ_json", "SAP Commerce OCC JSON"),
                            ("bootstrap_json", "Category-page bootstrap JSON"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=30,
                    ),
                ),
                ("heartbeat_enabled", models.BooleanField(default=False)),
                ("fast_lane", models.BooleanField(default=False)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("backing_off", "Backing off"),
                            ("paused_pending_fix", "Paused pending fix"),
                            ("skip", "Skip (permanent)"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("consecutive_parser_rot", models.PositiveIntegerField(default=0)),
                ("clean_polls", models.PositiveIntegerField(default=0)),
                ("backoff_until", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("bucket_rate_per_min", models.FloatField(default=6.0)),
                ("bucket_burst", models.PositiveIntegerField(default=3)),
                ("misfire_grace_s", models.PositiveIntegerField(default=60)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "source_config",
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="is_international",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offersnapshot",
            name="usd_item_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("item_price"), "*", models.F("fx_rate")
                ),
                output_field=models.DecimalField(decimal_places=4, max_digits=14),
            ),
        ),
        migrations.AddConstraint(
            model_name="offersnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("currency", "USD"),
                    models.Q(
                        ("fx_rate__isnull", False),
                        models.Q(("fx_pair", ""), _negated=True),
                        ("fx_rate_date__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="offer_snapshot_fx_stamped_non_usd",
            ),
        ),
        migrations.AddConstraint(
            model_name="fxratedaily",
            constraint=models.UniqueConstraint(
                fields=("rate_date", "base", "quote"), name="fx_rate_daily_unique_pair_date"
            ),
        ),
        migrations.AddField(
            model_name="scraperrun",
            name="source_site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="runs",
                to="catalog.sourcesite",
            ),
        ),
        migrations.AddField(
            model_name="sourceconfig",
            name="source_site",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="config",
                to="catalog.sourcesite",
            ),
        ),
        migrations.AddIndex(
            model_name="scraperrun",
            index=models.Index(
                fields=["source_site", "-started_at"], name="scraper_runs_site_started"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(("cadence_ceiling_s__lte", models.F("cadence_baseline_s"))),
                name="source_config_ceiling_lte_baseline",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fast_lane", False),
                    models.Q(
                        ("volatility_profile", "drop_prone"),
                        models.Q(("cheap_signal", "none"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="source_config_fast_lane_eligible",
            ),
        ),
    ]
