# Generated by Django 6.0.6 on 2026-07-05 14:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_seed_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="product_family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="catalog.productfamily",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="product_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="catalog.productmodel",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="resolution_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="resolution_grain",
            field=models.CharField(
                choices=[
                    ("none", "Unresolved"),
                    ("family", "Product family"),
                    ("model", "Product model"),
                    ("variant", "Product variant"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="condition",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("recertified", "Recertified"),
                    ("refurbished", "Refurbished"),
                    ("used", "Used"),
                    ("open_box", "Open box"),
                    ("for_parts", "For parts / not working"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ListingResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "grain",
                    models.CharField(
                        choices=[
                            ("none", "Unresolved"),
                            ("family", "Product family"),
                            ("model", "Product model"),
                            ("variant", "Product variant"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("source_alias", "Rung 0 — re-observation"),
                            ("exact_alias", "Rung 1 — exact alias"),
                            ("mpn_decode", "Rung 2 — grammar decode"),
                            ("attribute_match", "Rung 3 — attribute match"),
                            ("manual", "Rung 4 — manual"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("matcher_version", models.CharField(max_length=20)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("resolved_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="catalog.listing",
                    ),
                ),
                (
                    "product_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolutions",
                        to="catalog.productfamily",
                    ),
                ),
                (
                    "product_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolutions",
                        to="catalog.productmodel",
                    ),
                ),
                (
                    "product_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolutions",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supersedes",
                        to="catalog.listingresolution",
                    ),
                ),
            ],
            options={
                "db_table": "listing_resolution",
                "indexes": [
                    models.Index(fields=["listing", "-resolved_at"], name="listing_res_recent")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("grain", "none"),
                                ("product_family__isnull", True),
                                ("product_model__isnull", True),
                                ("product_variant__isnull", True),
                            ),
                            models.Q(
                                ("grain", "family"),
                                ("product_family__isnull", False),
                                ("product_model__isnull", True),
                                ("product_variant__isnull", True),
                            ),
                            models.Q(
                                ("grain", "model"),
                                ("product_family__isnull", True),
                                ("product_model__isnull", False),
                                ("product_variant__isnull", True),
                            ),
                            models.Q(
                                ("grain", "variant"),
                                ("product_family__isnull", True),
                                ("product_model__isnull", True),
                                ("product_variant__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="listing_resolution_grain_target_coherent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("grain", "none"),
                            models.Q(
                                models.Q(("method", ""), _negated=True),
                                ("confidence__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="listing_resolution_accept_carries_method",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("listing",),
                        name="listing_resolution_one_current",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_current", False), ("superseded_by__isnull", True), _connector="OR"
                        ),
                        name="listing_resolution_current_not_superseded",
                    ),
                ],
            },
        ),
    ]
