# Generated by Django 6.0.6 on 2026-07-06 00:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_backfill_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefdataConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("discovery_occurrence_threshold", models.PositiveIntegerField(default=3)),
                ("last_refresh_at", models.DateTimeField(blank=True, null=True)),
                ("last_report_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "refdata_config",
            },
        ),
        migrations.CreateModel(
            name="ReferenceFetchRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hypothesis_key", models.CharField(max_length=300, unique=True)),
                ("mpn_hypothesis", models.CharField(max_length=200)),
                ("vendor_hint", models.CharField(blank=True, default="", max_length=50)),
                ("occurrences_at_enqueue", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "reference_fetch_request",
            },
        ),
        migrations.AddField(
            model_name="listingresolution",
            name="last_evaluated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
