# Generated by Django 6.0.6 on 2026-07-06 06:49
#
# Hand-adjusted after generation: the autodetector split each model's
# `source_site` ForeignKey into a separate AddField after CreateModel (a
# known autodetector quirk, cf. Django tickets #23956/#27768 for new models
# added in the same run). For AvailabilityHeartbeatObservation this is fatal,
# not just suboptimal: `pk = CompositePrimaryKey("source_site_id", ...)`
# needs the source_site_id column to exist in the same CREATE TABLE
# statement, so migrate raised FieldDoesNotExist. Fix: inline `source_site`
# into each CreateModel's fields (matches the sanctioned fix in #23956) and
# drop the two AddField ops. No behavior change vs. the model state.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_refdata_seed"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilityHeartbeatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                            ("availability_heartbeat", "Availability heartbeat (30d)"),
                            ("availability_heartbeat_event", "Heartbeat event (365d)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("source_sku", models.CharField(max_length=255)),
                ("observed_at", models.DateTimeField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("transition_detected", "Transition detected"),
                            ("ambiguous", "Ambiguous"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("prev_fingerprint", models.CharField(blank=True, default="", max_length=64)),
                ("fingerprint", models.CharField(max_length=64)),
                ("detail_json", models.JSONField(blank=True, default=dict)),
                (
                    "source_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="heartbeat_events",
                        to="catalog.sourcesite",
                    ),
                ),
            ],
            options={
                "db_table": "availability_heartbeat_event",
            },
        ),
        migrations.CreateModel(
            name="AvailabilityHeartbeatObservation",
            fields=[
                (
                    "retention_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("merchant_fact", "Merchant fact (indefinite)"),
                            ("ebay_listing_observation", "eBay observation"),
                            ("amazon_ephemeral", "Amazon ephemeral"),
                            ("amazon_identifier", "Amazon identifier (indefinite)"),
                            ("transient_discovery", "Search-provider discovery"),
                            ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                            ("manufacturer_reference", "Manufacturer reference"),
                            ("availability_heartbeat", "Availability heartbeat (30d)"),
                            ("availability_heartbeat_event", "Heartbeat event (365d)"),
                        ],
                        max_length=40,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "source_site_id",
                        "source_sku",
                        "observed_at",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="heartbeats",
                        to="catalog.sourcesite",
                    ),
                ),
                ("source_sku", models.CharField(max_length=255)),
                ("observed_at", models.DateTimeField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("unchanged", "Unchanged"),
                            ("transition_detected", "Transition detected"),
                            ("ambiguous", "Ambiguous"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("stock_status", models.CharField(blank=True, default="", max_length=20)),
                (
                    "shipping_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("http_status", models.PositiveSmallIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("endpoint", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "availability_heartbeat_observation",
            },
        ),
        migrations.RemoveConstraint(
            model_name="listing",
            name="listing_retention_ttl_coherent",
        ),
        migrations.RemoveConstraint(
            model_name="offersnapshot",
            name="offer_snapshot_retention_ttl_coherent",
        ),
        migrations.RemoveConstraint(
            model_name="rawpayload",
            name="raw_payload_retention_ttl_coherent",
        ),
        migrations.RemoveConstraint(
            model_name="searchobservation",
            name="search_observation_retention_ttl_coherent",
        ),
        migrations.RemoveConstraint(
            model_name="verificationevent",
            name="verification_event_retention_ttl_coherent",
        ),
        migrations.AlterField(
            model_name="drivespec",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="offersnapshot",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="productalias",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="rawpayload",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="searchobservation",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="verificationevent",
            name="retention_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant_fact", "Merchant fact (indefinite)"),
                    ("ebay_listing_observation", "eBay observation"),
                    ("amazon_ephemeral", "Amazon ephemeral"),
                    ("amazon_identifier", "Amazon identifier (indefinite)"),
                    ("transient_discovery", "Search-provider discovery"),
                    ("tavily_extract", "Tavily-extracted fact (indefinite)"),
                    ("manufacturer_reference", "Manufacturer reference"),
                    ("availability_heartbeat", "Availability heartbeat (30d)"),
                    ("availability_heartbeat_event", "Heartbeat event (365d)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="listing_retention_ttl_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="offersnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="offer_snapshot_retention_ttl_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawpayload",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="raw_payload_retention_ttl_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="searchobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="search_observation_retention_ttl_coherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="verificationevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="verification_event_retention_ttl_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityheartbeatevent",
            index=models.Index(fields=["source_site", "-observed_at"], name="hb_event_site_time"),
        ),
        migrations.AddConstraint(
            model_name="availabilityheartbeatevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_class", ""), _negated=True),
                name="availability_heartbeat_event_retention_class_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityheartbeatevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="availability_heartbeat_event_retention_ttl_coherent",
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityheartbeatobservation",
            index=models.Index(
                fields=["source_site", "source_sku", "-observed_at"], name="hb_obs_sku_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityheartbeatobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("retention_class", ""), _negated=True),
                name="availability_heartbeat_observation_retention_class_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityheartbeatobservation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("expires_at__isnull", True),
                        (
                            "retention_class__in",
                            [
                                "merchant_fact",
                                "amazon_identifier",
                                "tavily_extract",
                                "manufacturer_reference",
                            ],
                        ),
                    ),
                    models.Q(
                        ("expires_at__isnull", False),
                        (
                            "retention_class__in",
                            [
                                "ebay_listing_observation",
                                "amazon_ephemeral",
                                "transient_discovery",
                                "availability_heartbeat",
                                "availability_heartbeat_event",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="availability_heartbeat_observation_retention_ttl_coherent",
            ),
        ),
    ]
